### ISSUE TITLE
Easy way to allow NETStandard packages to work in PCL's in VS2012-2015?

### ISSUE THREAD

**Issue by DamienDennehy** [davidfowl/NetStandard#5]
If you create a Class Library Package using NETStandard (or dotnet in RC1), the library won't work in a PCL in Visual Studio 2012-2015.

![missingprofilefiles](https://cloud.githubusercontent.com/assets/3924814/14582159/81ab655a-03f5-11e6-9f3b-21ae52052a66.png)

This is because the PCL is expecting a Profile directory such as Profile111 - "portable-net45+netcore45+wpa81".

So you've got a couple of choices to fix this.
1. Create a script to copy the NETStandard DLL into a portable-net45+netcore45+wpa81 folder.
2. You can add the profile as a framework in the project.json file (but sometimes this doesn't work depending on your other framework targets, see [Autofac's problems on this](http://www.paraesthesia.com/archive/2015/10/20/gotcha-with-dnx-dependency-resolution-dotnet-pcl/)).

Neither of these options are perfect and it would be great to have a foolproof way of doing this.

**Comment by davidfowl** [comment]
> If you create a Class Library Package using NETStandard (or dotnet in RC1), the library won't work in a PCL in Visual Studio 2012-2015.

It works in Visual Studio 2015 if you made the package correctly and use Visual Studio 2015 Update 2 with NuGet >= 3.4. The NuGet team is looking at making this work on down level Visual Studio in the future.

> Create a script to copy the NETStandard DLL into a portable-net45+netcore45+wpa81 folder.

This is the solution for now. Put the same DLL in a portable-\* folder. That way it will be recognized by both old and new versions of Visual Studio.

> You can add the profile as a framework in the project.json file (but sometimes this doesn't work depending on your other framework targets, see Autofac's problems on this).

Most of those problems are resolved with netstandard.

Aside: Can you show me how you authored DemoClassLibrary?

**Comment by DamienDennehy** [comment]
The Demo Library was pretty much a standard Class Library Package.
I tried this again using VS2015 Update 2 and NuGet 3.4.2 and I can replicate it :/
1. Create a new Class Library Package targeting .NET Framework 4.5.
   ![newclasslibrary](https://cloud.githubusercontent.com/assets/3924814/14582613/3041f8f2-0402-11e6-84b1-ca3ec0d5fd76.jpg)
2. Downgrade the frameworks in project.json to net45 and dotnet5.2 and downgrade the dependencies from betas to stable 4.0 versions. ([project.json here](https://gist.github.com/DamienDennehy/8c8e45f13a9ff54999f10cc9cd34797a)).
3. Set "Produce outputs on build", build the project and you'll get the NuGet package in the artifacts folder.
4. Create a local NuGet repository on your machine (just a directory) and pop the package in there.
   ![nugetfolder](https://cloud.githubusercontent.com/assets/3924814/14582633/ce5a92ba-0402-11e6-985f-e939328dd4d5.jpg)
5. Add the reference to the local NuGet repository in VS.
   ![nugetlocal](https://cloud.githubusercontent.com/assets/3924814/14582662/58a05f4a-0403-11e6-929c-80fbad134804.jpg)
6. Create a new Portable Class Library targeting .NET Framework 4.5.
   ![pcl](https://cloud.githubusercontent.com/assets/3924814/14582674/a857fd7c-0403-11e6-9a2e-f4565fb9768d.jpg)
7. Select the following targets to get Profile111.
   ![selecttargets](https://cloud.githubusercontent.com/assets/3924814/14582686/1825a8fc-0404-11e6-9808-2022b323e3ed.jpg)
8. Add the DemoLibrary NuGet package created earlier using the NuGet Package Manager.
   ![nugetpackagemanager](https://cloud.githubusercontent.com/assets/3924814/14582705/812f9b64-0404-11e6-8b06-96319d2e1310.jpg)
9. After hitting Install, you'll get an error.
   ![error](https://cloud.githubusercontent.com/assets/3924814/14582716/b627e326-0404-11e6-834d-a281f3a0ad0b.jpg)

The DemoLibrary package installs fine in other project types.

**Comment by davidfowl** [comment]
The library you made doesn't target the right target framework. We changed dotnet5.x into netstandard for Rc2 and there's no visual studio experience for that as yet. What you're experiencing is expected and what I described works in update 2.

**Comment by DamienDennehy** [comment]
Ah that's cool, I'll wait for RC2 then. Appreciate you looking into this!

**Comment by davidfowl** [comment]
This should be working with the latest nuget I believe

**Comment by DamienDennehy** [comment]
Thanks David.
